---
  - hosts: ntps
    gather_facts: false
    become: True
    roles:
      - ntp

  - hosts: pths
    gather_facts: false
    become: True
    roles:
      - prometheus

  - hosts: s3s
    gather_facts: false
    become: True
    roles:
      - s3cmd
