---
- name: 下载程序包
  get_url:
    url: "{{ item }}"
    dest: /tmp/
  with_items:
    - '{{ pkgs_site }}{{ pkgs_url }}/{{ docker_pkgs }}'
    - '{{ pkgs_site }}{{ pkgs_url }}/{{ etcd_pkgs }}'
    - '{{ pkgs_site }}{{ pkgs_url }}/{{ k8s_version }}/{{ k8s_pkgs }}'

- name: 解压程序包
  unarchive:
    src: "{{ item }}"
    dest: /tmp/
  with_items:
    - '/tmp/{{ docker_pkgs }}'
    - '/tmp/{{ etcd_pkgs }}'
    - '/tmp/{{ k8s_pkgs }}'
